import { Link } from "react-router-dom";

const sections: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "1. Scope of this Privacy Policy and Our Roles",
    paragraphs: [
      "1.1 This Privacy Policy applies to all personal information collected, held, used, or disclosed by Auditron in the course of operating the Service, regardless of the medium in which the information is held.",
      "1.2 Auditron handles personal information in two distinct capacities, and the obligations described in this Privacy Policy apply differently to each:",
      "(a) Auditron Account Information. Personal information about you (the registered user) and any other person you authorise to access your account, including name, email, business contact details, professional credentials, and account activity. In respect of Auditron Account Information, Auditron is the controller and is directly subject to the Privacy Act and the APPs.",
      "(b) Client Data. Documents, information, and data you upload to the Service for the purpose of conducting an SMSF audit, which may include personal information about your clients, their members, accountants, advisers, and other related individuals. In respect of personal information contained in Client Data, you are the independent controller and Auditron is a processor acting on your instructions, as recorded in clause 18.2 of the Terms of Service.",
      "1.3 You are solely responsible for the lawful collection, use, and disclosure of personal information contained in Client Data, including providing privacy notices and obtaining consents required under the Privacy Act, the APPs, and any other applicable law. Nothing in this Privacy Policy transfers that responsibility to Auditron.",
    ],
  },
  {
    heading: "2. Kinds of Personal Information We Collect",
    paragraphs: [
      "2.1 Auditron collects only the personal information reasonably necessary for, or directly related to, the operation of the Service. The kinds of information we collect include:",
      "(a) Identity and contact information. Your full name, email address, phone number, postal address, business name, ABN, professional registration details (including SMSF auditor number), and similar contact and identity information you provide on registration or update through your account.",
      "(b) Authentication information. Hashed passwords, multi-factor authentication tokens, session identifiers, and other credentials used to verify your identity.",
      "(c) Billing information. Billing name, billing address, payment method type, and the last four digits of your payment card. Full payment card numbers are collected and stored by our payment processor (Stripe) and are not stored by Auditron.",
      "(d) Usage and technical information. IP address, device type, browser type, operating system, log files, audit run identifiers, processing times, error reports, and similar technical and analytical information generated by your use of the Service.",
      "(e) Communications. Records of your correspondence with Auditron (including support tickets, emails, and in-product messages) and any feedback or suggestions you provide.",
      "(f) Client Data. Documents and information you upload for the purpose of conducting audits, which may contain personal information about third parties (including SMSF members, trustees, advisers, accountants, and related individuals), tax file numbers, financial information, and other sensitive information.",
      "2.2 Sensitive information. Some Client Data may constitute \"sensitive information\" within the meaning of the Privacy Act, including health information, government identifiers, and tax file numbers. You acknowledge that you are responsible for ensuring you have the consent or other lawful basis required under APP 3 to collect, hold, and disclose such information through the Service.",
      "2.3 Anonymous and pseudonymous interaction. Where lawful and practicable, you may interact with Auditron anonymously or under a pseudonym (for example, when making a general enquiry through our website). However, the Service cannot be used without a registered account and accurate identity information.",
    ],
  },
  {
    heading: "3. How We Collect Personal Information",
    paragraphs: [
      "3.1 We collect personal information in the following ways:",
      "(a) Directly from you, when you create an account, complete a profile, upload Client Data, configure settings, contact our support team, or otherwise interact with the Service.",
      "(b) Automatically, through cookies, log files, analytics tools, and similar technologies that record your interaction with the Service (see clause 12 – Cookies and Tracking Technologies).",
      "(c) From third parties, such as authentication providers (where you sign in using a third-party identity provider), payment processors (where they confirm a successful payment), and publicly available sources (such as ASIC and the Tax Practitioners Board) where verification of your professional credentials is reasonably required.",
      "3.2 Unsolicited information. If we receive personal information that we did not solicit, we will, within a reasonable period, determine whether we could have lawfully collected the information under APP 3. If we could not, we will destroy or de-identify it as soon as practicable, where lawful and reasonable to do so.",
      "3.3 Notification of collection. Where we collect personal information directly from an individual, we will take reasonable steps to make the matters set out in APP 5 known to that individual at or before the time of collection, including the purposes of collection and the consequences of failing to provide the information.",
    ],
  },
  {
    heading: "4. Purposes for Which We Collect, Hold, Use, and Disclose Personal Information",
    paragraphs: [
      "4.1 We collect, hold, use, and disclose personal information for the following primary purposes:",
      "(a) to register, authenticate, maintain, and administer your account;",
      "(b) to provide, operate, and improve the Service, including processing audits, generating draft findings, RFIs, opinions, working papers, and reports, and processing Client Data through the AI service providers described in clause 7;",
      "(c) to communicate with you about the Service, including sending operational notices, security alerts, updates, support responses, and (where you have not opted out) product updates;",
      "(d) to invoice you, process payments, and recover amounts owing;",
      "(e) to monitor, secure, and protect the integrity of the Service, detect and respond to fraud, misuse, or breach of the Terms of Service, and enforce our legal rights;",
      "(f) to comply with our legal, regulatory, and professional obligations, including our obligations under the Privacy Act, the Notifiable Data Breaches scheme, and any lawful direction or request from a regulator (see clause 8);",
      "(g) to generate aggregated, anonymised analytics and insights about use of the Service, in a form that does not identify you, your clients, or any other individual; and",
      "(h) for any related secondary purpose that you would reasonably expect, or for any other purpose with your consent or as otherwise permitted under APP 6.",
      "4.2 Direct marketing. We may use your contact details to send you direct marketing communications about the Service. You may opt out at any time by following the unsubscribe link in any marketing email or by contacting us at the address in clause 14. We do not sell or rent personal information to third parties for their marketing purposes.",
      "4.3 No use for AI model training. Auditron does not use Client Data to train, retrain, or fine-tune any artificial intelligence model owned or operated by Auditron, except where you expressly opt in. Our contractual arrangements with AI service providers (clause 7) prohibit them from using Client Data to train their generally available models.",
      "4.4 No automated decision-making with legal effect. The Service generates draft outputs only. No output of the Service produces a legal or similarly significant effect on any individual without independent professional review and decision-making by you, the registered auditor.",
    ],
  },
  {
    heading: "5. Storage Location and Cross-Border Disclosure",
    paragraphs: [
      "5.1 Australian data storage. All personal information collected or processed by Auditron in connection with the Service is stored on servers located in Australia. Auditron has selected Australian data centre regions for all infrastructure on which Auditron Account Information and Client Data are stored at rest.",
      "5.2 We do not transfer Client Data or Auditron Account Information to overseas servers in the ordinary course of providing the Service.",
      "5.3 Limited cross-border processing for AI inference. To generate AI-assisted outputs, the Service transmits relevant content (which may include personal information contained in Client Data) to one or more third-party large language model providers for processing in real time. Some of these providers process data on infrastructure located outside Australia, including in the United States. Personal information transmitted for AI inference is not retained by those providers for training or for any purpose beyond returning the output to Auditron, in accordance with their enterprise terms. The specific providers, their general processing locations, and their data handling commitments are set out in clause 7.",
      "5.4 APP 8 compliance. Where personal information is disclosed to an overseas recipient, Auditron takes reasonable steps to ensure that the recipient does not breach the APPs in relation to that information, including by entering into contractual arrangements requiring the recipient to handle the information in accordance with standards substantially similar to the APPs.",
      "5.5 Your acknowledgement. By using the Service, you acknowledge and consent to the cross-border processing described in clauses 5.3 and 7 for the limited purpose of AI inference. You acknowledge that, to the extent your consent constitutes consent for the purposes of APP 8.2(b), Auditron is not required to take the steps in APP 8.1 in respect of disclosures to those AI service providers.",
    ],
  },
  {
    heading: "6. Data Security",
    paragraphs: [
      "6.1 Auditron applies administrative, physical, and technical safeguards designed to protect personal information from misuse, interference, loss, and unauthorised access, modification, or disclosure, in accordance with APP 11.1.",
      "6.2 Our security measures include, without limitation:",
      "(a) encryption of personal information in transit using TLS 1.2 or higher;",
      "(b) encryption of personal information at rest using AES-256 or equivalent;",
      "(c) logical access controls, role-based permissions, and the principle of least privilege for personnel and systems;",
      "(d) multi-factor authentication for administrative access to production systems;",
      "(e) row-level security and tenant isolation within our application database;",
      "(f) audit logging of access to, and changes affecting, personal information;",
      "(g) regular security review of our infrastructure, dependencies, and AI service provider configurations; and",
      "(h) supplier due diligence and contractual security commitments with all sub-processors.",
      "6.3 Notwithstanding these measures, no system or transmission is completely secure. Auditron does not guarantee that personal information will not be subject to unauthorised access, loss, alteration, or disclosure. To the maximum extent permitted by law, Auditron's liability for any security incident is subject to and limited by clause 13 of the Terms of Service.",
      "6.4 Notifiable data breaches. If Auditron becomes aware of a data breach that is likely to result in serious harm to any individual whose personal information is involved, Auditron will assess and respond to the breach in accordance with the Notifiable Data Breaches scheme of Part IIIC of the Privacy Act, including notifying the Office of the Australian Information Commissioner and affected individuals where required. Where the breach involves Client Data, Auditron will provide you with sufficient information about the nature and scope of the breach to enable you to discharge your own notification obligations under clause 5.8 of the Terms of Service.",
      "6.5 User responsibilities. You must take reasonable steps to safeguard your account credentials, maintain up-to-date security practices on the devices you use to access the Service, and notify Auditron without undue delay (and in any event within 24 hours) of becoming aware of any actual or suspected unauthorised access to your account, in accordance with clause 5.9 of the Terms of Service.",
    ],
  },
  {
    heading: "7. Disclosure to Third Parties and AI Service Providers",
    paragraphs: [
      "7.1 We disclose personal information only as reasonably necessary to operate the Service, comply with the law, or enforce our rights. The categories of recipients are:",
      "(a) Cloud infrastructure providers (such as Amazon Web Services and Supabase) that host the Australian-region infrastructure on which the Service operates;",
      "(b) AI service providers (such as Anthropic, OpenAI, and Google) that process content transmitted by the Service for the limited purpose of generating AI outputs in real time, on enterprise terms that prohibit use of the content for training their generally available models;",
      "(c) Authentication and identity providers where you choose to sign in using a third-party identity service;",
      "(d) Payment processors (such as Stripe) that handle billing transactions;",
      "(e) Email, notification, and analytics providers that support communications, monitoring, and product analytics for the Service;",
      "(f) Professional advisers (such as lawyers, accountants, and auditors) bound by duties of confidentiality, where reasonably required;",
      "(g) Acquirers and successors in connection with any actual or prospective merger, acquisition, sale of assets, or similar transaction (and we will require any acquirer to honour the commitments in this Privacy Policy); and",
      "(h) Regulators, courts, and law enforcement as set out in clause 8.",
      "7.2 AI service provider commitments. Auditron uses AI service providers under enterprise contractual terms that include the following commitments: (a) data submitted via the API is not used to train the provider's generally available models; (b) data is retained only for the limited period necessary to deliver the service and comply with the provider's abuse-monitoring and legal obligations; and (c) data is processed under the security and confidentiality controls described in the provider's enterprise terms.",
      "7.3 No sale of personal information. Auditron does not sell, rent, or trade personal information.",
      "7.4 Public information. From time to time we may publish aggregated, de-identified statistics about use of the Service (for example, total audits processed). Such statistics will not identify you, your clients, or any other individual.",
    ],
  },
  {
    heading: "8. Disclosure to Regulators, Courts, and Law Enforcement",
    paragraphs: [
      "8.1 Auditron may disclose personal information (including Client Data and Auditron Account Information) where reasonably required to do so to:",
      "(a) the Australian Taxation Office;",
      "(b) the Australian Securities and Investments Commission;",
      "(c) the Australian Prudential Regulation Authority;",
      "(d) the Office of the Australian Information Commissioner;",
      "(e) the Australian Federal Police or other law enforcement agencies;",
      "(f) any court, tribunal, or arbitral body of competent jurisdiction;",
      "(g) any other regulator with lawful authority to require such disclosure; or",
      "(h) any party where disclosure is required by Australian law, court order, subpoena, or binding regulatory direction.",
      "8.2 Where lawful and practical, Auditron will use reasonable efforts to notify you in advance of any such disclosure to enable you to seek a protective order or otherwise object. Auditron is not required to notify you where notification is prohibited by law, court order, or where notification would prejudice an investigation.",
      "8.3 This clause 8 reflects, and operates consistently with, clause 19 of the Terms of Service (Regulatory Cooperation and Lawful Disclosure).",
    ],
  },
  {
    heading: "9. Retention and Deletion of Personal Information",
    paragraphs: [
      "9.1 Auditron retains personal information only for as long as reasonably necessary for the purposes set out in clause 4 or as required by law.",
      "9.2 Client Data export and deletion. While your account is active, you may export Client Data from the Service at any time. Following termination of your account, Client Data will remain available for export for ninety (90) days. After expiry of that ninety-day period, Auditron will permanently delete all Client Data within a further thirty (30) days, except where retention is required by law, regulation, or legitimate ongoing legal proceedings. Once deleted, Client Data cannot be recovered. This timetable corresponds to clause 5.6 of the Terms of Service.",
      "9.3 Auditron Account Information. We retain account information for as long as your account is active. After closure of your account, we may retain a limited subset of account information (such as billing records, audit logs, and identity verification records) for the period required by Australian taxation, accounting, anti-money laundering, and other applicable laws, and for the period reasonably necessary to defend against legal claims.",
      "9.4 Backups. Personal information may persist for a limited additional period in encrypted, isolated backup systems, after which it is overwritten in accordance with our backup rotation schedule.",
      "9.5 De-identification. Where Auditron no longer needs personal information for any purpose for which it may be used or disclosed, and is not required by law to retain it, Auditron will take reasonable steps to destroy or de-identify the information in accordance with APP 11.2.",
    ],
  },
  {
    heading: "10. Your Rights: Access, Correction, and Complaints",
    paragraphs: [
      "10.1 Right to access. You have the right under APP 12 to request access to the personal information Auditron holds about you. We will respond to access requests within a reasonable period (and, in any case, within 30 days). We may decline a request, or provide partial access, only on the limited grounds permitted under APP 12.3.",
      "10.2 Right to correction. You have the right under APP 13 to request that Auditron correct personal information about you that is inaccurate, out of date, incomplete, irrelevant, or misleading. Where we agree the information requires correction, we will make the correction at no charge. Where we disagree, you may request that we associate a statement with the information noting your view.",
      "10.3 Requests in respect of Client Data. Requests for access to, or correction of, personal information contained in Client Data must be directed to you, the controller of that information. Where Auditron receives a request relating to Client Data, Auditron will, where lawful and practical, refer the request to you and provide reasonable assistance to enable you to respond.",
      "10.4 How to make a request. To request access to or correction of your personal information, contact us using the details in clause 14. We may require verification of your identity before processing a request.",
      "10.5 Complaints. If you believe Auditron has breached the APPs or this Privacy Policy, you may make a complaint to us using the details in clause 14. We will acknowledge your complaint within 7 days and provide a substantive response within 30 days. If you are not satisfied with our response, you may lodge a complaint with the Office of the Australian Information Commissioner at oaic.gov.au or by calling 1300 363 992.",
      "10.6 No fee. Auditron does not charge a fee for making a privacy request or complaint, or for correcting personal information. We may charge a reasonable fee for the costs of providing access in particular formats, where permitted by APP 12.8.",
    ],
  },
  {
    heading: "11. Children",
    paragraphs: [
      "11.1 The Service is intended for use by registered SMSF auditors and other professional users. The Service is not directed at, and we do not knowingly collect personal information directly from, individuals under 18 years of age. If you become aware that a child has provided personal information to Auditron without appropriate consent, please contact us using the details in clause 14 so that we may take appropriate steps.",
      "11.2 Client Data may include information about minors (for example, members of an SMSF who are under 18). You are responsible for ensuring you have the consent or other lawful basis required to upload such information.",
    ],
  },
  {
    heading: "12. Cookies and Tracking Technologies",
    paragraphs: [
      "12.1 Auditron uses cookies, local storage, and similar technologies to operate the Service, maintain your session, remember your preferences, secure your account, and analyse use of the Service.",
      "12.2 We use the following categories of cookies and similar technologies:",
      "(a) Strictly necessary, to authenticate your session and operate core features. These cannot be disabled without preventing the Service from functioning.",
      "(b) Functional, to remember your preferences and settings.",
      "(c) Analytics, to understand how the Service is used in aggregate and to identify and fix issues. We use privacy-respecting analytics tools that do not, on their own, identify individual users.",
      "12.3 We do not use third-party advertising cookies or share your usage data with advertising networks.",
      "12.4 Most browsers allow you to refuse or delete cookies. Disabling strictly necessary cookies will prevent you from using the Service.",
    ],
  },
  {
    heading: "13. Changes to this Privacy Policy",
    paragraphs: [
      "13.1 Auditron may update this Privacy Policy from time to time to reflect changes to the Service, our practices, or applicable law. The current version is identified by the effective date at the top of this document.",
      "13.2 Where a change is material, Auditron will provide reasonable notice to you (for example, by email or in-product notification) before the change takes effect. Your continued use of the Service after the effective date of any change constitutes acceptance of the updated Privacy Policy.",
      "13.3 Prior versions of this Privacy Policy will be made available on request to the contact address in clause 14.",
    ],
  },
  {
    heading: "14. How to Contact Us",
    paragraphs: [
      "14.1 If you have any questions about this Privacy Policy, wish to exercise any right under it, or wish to make a privacy complaint, you may contact our Privacy Officer using the details below.",
      "14.2 Privacy Officer, Auditron",
      "(a) Entity: Orkid Puri Pty Ltd (ABN 48 617 154 819) trading as Auditron",
      "(b) Email: privacy@auditron.com.au",
      "(c) Postal address: South Australia, Australia (full postal address available on request)",
      "14.3 External oversight. The Office of the Australian Information Commissioner is the independent regulator responsible for privacy in Australia. You may contact the OAIC at:",
      "(a) Website: www.oaic.gov.au",
      "(b) Phone: 1300 363 992",
      "(c) Postal address: GPO Box 5288, Sydney NSW 2001.",
    ],
  },
];

export default function Privacy() {
  const headingStyle: React.CSSProperties = {
    fontFamily: "'Open Sans', sans-serif",
    fontWeight: 700,
    fontSize: "20px",
    color: "#111111",
    margin: "40px 0 16px",
    letterSpacing: "-0.01em",
  };
  const bodyStyle: React.CSSProperties = {
    fontFamily: "'Open Sans', sans-serif",
    fontWeight: 400,
    fontSize: "15px",
    lineHeight: 1.7,
    color: "#333333",
    margin: "0 0 14px",
  };

  return (
    <div style={{ background: "#ffffff", minHeight: "100vh" }}>
      <header style={{ borderBottom: "1px solid #eeeeee", padding: "20px 32px", background: "#ffffff" }}>
        <div className="mx-auto flex items-center justify-between" style={{ maxWidth: "1100px" }}>
          <Link to="/" style={{ fontFamily: "'Open Sans', sans-serif", fontWeight: 700, fontSize: "18px", color: "#111111", textDecoration: "none" }}>
            Auditron
          </Link>
          <Link to="/" style={{ fontFamily: "'Open Sans', sans-serif", fontSize: "14px", color: "#555555", textDecoration: "none" }}>
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto" style={{ maxWidth: "780px", padding: "64px 32px 96px" }}>
        <h1 style={{ fontFamily: "'Open Sans', sans-serif", fontWeight: 700, fontSize: "44px", color: "#111111", letterSpacing: "-0.02em", textAlign: "center", margin: "0 0 8px" }}>
          Auditron
        </h1>
        <h2 style={{ fontFamily: "'Open Sans', sans-serif", fontWeight: 600, fontSize: "26px", color: "#111111", textAlign: "center", margin: "0 0 16px" }}>
          Privacy Policy
        </h2>
        <p style={{ ...bodyStyle, textAlign: "center", color: "#555555" }}>
          Orkid Puri Pty Ltd (ABN 48 617 154 819) trading as Auditron
        </p>

        <p style={{ ...bodyStyle, marginTop: "32px" }}>
          This Privacy Policy explains how Orkid Puri Pty Ltd (ABN 48 617 154 819) trading as Auditron ("Auditron", "we", "us", or "our") collects, holds, uses, discloses, secures, and disposes of personal information in connection with the Auditron platform (the "Service").
        </p>
        <p style={bodyStyle}>
          Auditron is an Australian company with its registered office in South Australia. We are bound by the Privacy Act 1988 (Cth) ("Privacy Act") and the thirteen Australian Privacy Principles ("APPs") set out in Schedule 1 to that Act. This Privacy Policy is published in compliance with APP 1.3.
        </p>
        <p style={bodyStyle}>
          This Privacy Policy forms part of the Auditron Terms of Service. Capitalised terms not defined here have the meaning given to them in the Terms of Service. By creating an account, accessing, or using the Service, you confirm that you have read and understood this Privacy Policy.
        </p>
        <p style={bodyStyle}>
          All personal information held by Auditron in connection with the Service is stored on servers located in Australia. Auditron does not transfer personal information outside Australia in the ordinary course of providing the Service, except as expressly described in clause 7 (Disclosure to Third Parties and AI Service Providers).
        </p>
        <p style={{ ...bodyStyle, fontWeight: 700 }}>
          PLEASE READ THIS PRIVACY POLICY CAREFULLY. IT DESCRIBES IMPORTANT INFORMATION ABOUT HOW WE HANDLE YOUR PERSONAL INFORMATION, YOUR RIGHTS UNDER AUSTRALIAN PRIVACY LAW, AND THE LIMITS OF OUR RESPONSIBILITY IN RESPECT OF PERSONAL INFORMATION CONTAINED IN CLIENT DATA YOU UPLOAD.
        </p>

        {sections.map((s) => (
          <section key={s.heading}>
            <h3 style={headingStyle}>{s.heading}</h3>
            {s.paragraphs.map((p, i) => (
              <p key={i} style={bodyStyle}>{p}</p>
            ))}
          </section>
        ))}

        <h3 style={headingStyle}>Acknowledgement</h3>
        <p style={bodyStyle}>
          By creating an account, accessing, or using the Service, you confirm that you have read this Privacy Policy in full, understood it, and agree to the handling of your personal information as described. Where you upload Client Data, you confirm that you are authorised to do so and that you accept the responsibilities of an independent controller of the personal information contained in that Client Data.
        </p>
        <p style={{ ...bodyStyle, marginTop: "32px", color: "#555555" }}>
          Orkid Puri Pty Ltd trading as Auditron<br />
          ABN 48 617 154 819 · South Australia, Australia
        </p>
      </main>

      <footer style={{ background: "#0a0a0a", borderTop: "1px solid #1a1a1a", padding: "32px" }}>
        <div className="mx-auto flex flex-col md:flex-row items-center justify-between gap-4" style={{ maxWidth: "1100px" }}>
          <span style={{ fontFamily: "'Open Sans', sans-serif", fontSize: "13px", color: "#555555" }}>© 2026 Auditron Australia. All rights reserved.</span>
          <Link to="/" style={{ fontFamily: "'Open Sans', sans-serif", fontSize: "13px", color: "#555555", textDecoration: "none" }}>Home</Link>
        </div>
      </footer>
    </div>
  );
}
