// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puxbjitnqpsxixxilxsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1eGJqaXRucXBzeGl4eGlseHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTA3NzksImV4cCI6MjA4ODUyNjc3OX0.CewODdfi4UZ6ylWwJrw4GSu34pRF9VM7lGf5ZYA8oms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});